include: package:flutter_lints/flutter.yaml

linter:
  rules:
    ### Lint Paketinde [Ekli Olanlar]###
    # print() fonksiyonunu kullanma #
    avoid_print: true
    # Parametresiz Container kullanma #
    avoid_unnecessary_containers: true
    # Boşluk eklerken SizedBox'ı tercih et#
    sized_box_for_whitespace: true
    
    ### [Eklediklerim] ###
    # lib/ dizini içindekiler için Relative import'u tercih et#
    prefer_relative_imports: true
    # Birden fazla parametre olduğunda sona virgül ekle #
    require_trailing_commas: true
    # DecoratedBox'ı tercih et
    use_decorated_box: true
    # ColoredBox'ı tercih et #
    use_colored_box: true
    # Gereksiz Argüman kullanımdan kaçın #
    avoid_redundant_argument_values: true