name: ypyprojeodevi
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  hidden_drawer_menu: ^3.0.1
  cupertino_icons: ^1.0.5
  google_nav_bar: ^5.0.6
  cached_network_image: ^3.2.3
  firebase_auth: ^4.6.2
  cloud_firestore: ^4.8.0
  provider: ^6.0.5
  google_sign_in: ^6.1.4
  shared_preferences: ^2.1.2
  random_string: ^2.3.1
  firebase_core: ^2.13.1
  firebase_storage: ^11.2.2
  image_picker: ^0.8.8
  flutter_riverpod: ^2.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/